### ISSUE TITLE
Sending PASS command with colons in the password

### ISSUE THREAD

**Issue by AvonGenesis** [sorcix/irc#16]
Having a colon in the server password will cause it to be interpreted as a parameter.

```
message := irc.ParseMessage("PASS oauth:token_goes_here")
println(message.String()) // PASS oaut :token_goes_here
```

Discovered this when trying to connect to the [Twitch IRC](https://github.com/justintv/Twitch-API/blob/master/IRC.md#upon-a-successful-connection) servers. Not sure if its something you guys want to fix or not.

Got around it by creating a Message type directly.
```
message := &irc.Message{
      Command:  irc.PASS,
      Trailing: "oauth:token_goes_here",
    }
```

**Comment by belak** [comment]
Pull Request #13 would fix this, but it also performs worse, so it's sort of on hold.

**Comment by MorpheusXAUT** [comment]
I am currently using this library for connecting to the Twitch IRC servers as well and noticed something similar.

I solved the issue by "manually" constructing the IRC messages to be sent upon connection:
```
err := c.SendMessage(&irc.Message{
  Command: irc.PASS,
  Params:  []string{c.Config.IRCPassword},
})

if err != nil {
  return err
}
```
where c.SendMessage would encode an *irc.Message to an *irc.Encoder. Using this, I can also connect to Twitch servers just fine (beside the sometimes quite weird IRC implementation by Twitch, but that's a different topic :smile: )

**Comment by belak** [comment]
Also, this should work:

```
message := irc.ParseMessage("PASS :oauth:token_goes_here")
```

The trailing argument begins with a :, so there is definitely a bug in parsing though.

**Comment by sorcix** [comment]
A temporary fix is in branch [colon-in-param](https://github.com/sorcix/irc/tree/colon-in-param). Could you test your code with the fix, @AvonGenesis?

As @belak mentioned, a more thorough change in message parsing is coming.

**Comment by AvonGenesis** [comment]
@sorcix The code in that branch works. Thanks!

**Comment by sorcix** [comment]
This is now merged in master.
