### ISSUE TITLE
RPL_ISUPPORT support

### ISSUE THREAD

**Issue by Aerdan** [sorcix/irc#17]
Pretty much all modern IRC networks use ircds which provide information on their configuration in `RPL_ISUPPORT`, numeric `005`. It would thusly be preferential to allow for code using this library to be able to access a given connection's set of features, particularly since this impacts multiplexing joins, parts, PMs, and other commands as well as allowing erroneous mode changes to be caught before reaching the server.

**Comment by sorcix** [comment]
Understanding the IRC protocol is outside the scope of the `irc` package, it only provides the IRC messages as a struct. It may be useful to provide a subpackage to further decode these messages, similar to `irc/ctcp`.

I currently don't have the time to implement this, feel free to open a pull request!

**Comment by Aerdan** [comment]
If understanding the IRC protocol is outside the scope of this package, then perhaps `constants.go` needs to go. Aside from the lists of commands and numerics, all of that information can be derived from `RPL_ISUPPORT` (`PREFIX` for privileges and privilege sigils, `MODES` for the available modes, `CHANTYPES` for supported channel types, and so on and so forth).

**Comment by sorcix** [comment]
I agree that the mode characters should not be in this package, but I can't remove them at this point. They have to stay for backwards compatibility.
