### ISSUE TITLE
Fix ctcp package for go 1.0 and 1.1

### ISSUE THREAD

**Issue by belak** [sorcix/irc#21]
`strings_legacy.go` in the root of the repo is for go 1.0 and 1.1, however the travis config allows failures for these two versions. It appears that the ctcp package doesn't work with these versions because it uses strings.IndexByte rather than the helper.

Either 1.0 and 1.1 should be dropped, or the ctcp package should be updated to use the helper.

EDIT: There's a comment in strings_legacy.go that it can be dropped when wheezy is no longer supported, so I guess it should be fixed.

**Comment by belak** [comment]
So, in order to fix it, we'd either need to export irc.IndexByte, or copy the files into the ctcp package.

**Comment by sorcix** [comment]
The only thing left is the benchmarks error, as far as I can see. As those benchmark results make no sense due to the slow builds in the free version of Travis, we could simply disable benchmarks again. The only reason I've enabled them is because the additional code could be seen as a test.

**Comment by belak** [comment]
If we're worried about test coverage, perhaps disabling that and enabling a service like coveralls would be an option.
