### ISSUE TITLE
package gopkg.in/sorcix/irc.v1/internal: cannot find package "gopkg.in/sorcix/irc.v1/internal"

### ISSUE THREAD

**Issue by danbrakeley** [sorcix/irc#25]
I am unable to `go get github.com/sorcix/irc`. I have been `go get`ing a bunch of other packages, and this so far is the only one giving me problems.

```
proletariat@ubuntu:~/dev/src$ echo $GOPATH
/home/proletariat/dev
proletariat@ubuntu:~/dev/src$ pwd
/home/proletariat/dev/src
proletariat@ubuntu:~/dev/src$ rm -rf github.com/sorcix/
proletariat@ubuntu:~/dev/src$ go get github.com/sorcix/irc
package gopkg.in/sorcix/irc.v1/internal: cannot find package "gopkg.in/sorcix/irc.v1/internal" in any of:
        /usr/lib/go/src/gopkg.in/sorcix/irc.v1/internal (from $GOROOT)
        /home/proletariat/dev/src/gopkg.in/sorcix/irc.v1/internal (from $GOPATH)
```

**Comment by sorcix** [comment]
Looks like yesterdays change broke go get when using the github.com address, `go get gopkg.in/sorcix/irc.v1` seems to work fine.

As most people still use the github address I might want to revert that change in master.

**Comment by sorcix** [comment]
I have reverted yesterday's change till we find a solution for this problem.

**Comment by danbrakeley** [comment]
Confirmed fixed, thanks!
