### ISSUE TITLE
Messages ending in a whitespace are not parsed correctly

### ISSUE THREAD

**Issue by stapelberg** [sorcix/irc#7]
Due to calling `strings.Trim()` with the cutset containing `\r`, `\n`, `\x20` and `\x00`, messages with a trailing space at the end have that trailing space removed during parsing.

I looked at https://tools.ietf.org/html/rfc1459#section-2.3.1, and based on that I think we should only strip `\r` and `\n` as they are part of the framing.

If you want to sanity-check that there’s no `\x00` in the message, the current code is not sufficient, so we might as well remove `\x00` from the cutset and possibly add a proper check.

With regards to `\x20` being in the cutset, I don’t see what purpose it serves. Was that a mistake or could you please explain why that’s in the code? :)

Test program:

```go
package main

import (
    "fmt"

    "github.com/sorcix/irc"
)

func main() {
    m1 := irc.ParseMessage(":foo 375 stapelberg :- Message of the day - ")
    m2 := &irc.Message{
        Prefix:   &irc.Prefix{Name: "foo"},
        Command:  "375",
        Params:   []string{"stapelberg"},
        Trailing: "- Message of the day - ",
    }
    if string(m1.Bytes()) != string(m2.Bytes()) {
        fmt.Printf("broken, m1 = %q, m2 = %q\n", string(m1.Bytes()), string(m2.Bytes()))
    }
}
```

**Comment by sorcix** [comment]
I decided to strip `\x20` as people may want to decode messages from sources where they may be padded with spaces (logs, ..). As I was already stripping `\r` and `\n` anyway, it was an easy solution. As you pointed out, I didn't really think it through.

Removing `\x20` from the cutset fixes this. I might add a separate function with a decent optional sanity check.
