### ISSUE TITLE
Trailing should not be separate from params

### ISSUE THREAD

**Issue by belak** [sorcix/irc#8]
https://tools.ietf.org/html/rfc1459#section-2.3.1

`"After extracting the parameter list, all parameters are equal, whether matched by <middle> or <trailing>. <Trailing> is just a syntactic trick to allow SPACE within parameter."`

This currently leads to some annoyances with messages, as between different servers, the same message could be sent differently. And there is no way (currently) to tell an empty trailing from a missing one.

I'm not sure how you'd want to handle this since it would be a breaking change if Message.Trailing were dropped.

**Comment by sorcix** [comment]
The obvious fix would be:

```
Allparams []string
Params []string // = Allparams[:len(Allparams)-2] in case there is a Trailing argument
Trailing string // = Allparams[len(Allparams)-1] in case there is a Trailing argument
```

This would keep the current separate trailing parameter without too much overhead.

**Comment by belak** [comment]
This currently breaks some bots for me, as some IRC servers respond using the same messages (some networks using trailing for certain messages and some not). If a bot is only designed to work on a single network this is usually not an issue, however my current bot needs to run on both freenode and unreal. It's because of this that I think it's worth it.

It would also be nice to drop my irc package and just focus on the client aspect, since this library seems really nice otherwise. When I implemented this, I just added it to Params and made Trailing() always return the last param. However, this library appears to be used a bit more than mine. ;)

What about adding RawParams and something like a HasTrailing bool?

**Comment by sorcix** [comment]
I have changed my mind. Adding another slice containing all parameters is a bad solution. It works when decoding to a struct but introduces new issues during encoding in the `String()` and `Bytes()` methods. Should the parameter list be read from `RawParams` or `Params`?

Would a read-only solution suffice? A method that returns `append(params, trailing)`. That means that you'll still have to use `Trailing` if you want to modify the struct. As the spec says that all parameters are equal: Unless it includes spaces, it shouldn't matter if you put your last paramter in `Params` or in `Trailing`. Right?

Adding a few functions to help with this issue may be a better solution than introducing more fields in the struct. I'm afraid that would just add more bloat over time.

**Comment by belak** [comment]
In all honesty, if there was just a reliable way to determine if there was a trailing param, that should be enough and shouldn't break very much. Though I suppose this could also confuse encoding as well. :/

**Comment by belak** [comment]
If you're completely dead set on maintaining compatibility, this isn't an option, but I'd personally just remove `Trailing` and `EmptyTrailing`. If everything is a param, there isn't much use in treating them differently.

Alternatively, `EmptyTrailing` could be used (I guess)... using the same semantics as documented in stringifying messages. So, if `EmptyTrailing` is True and `Trailing == ""` you know that there was a trailing arg, but it was empty.

Similarly, `Trailing` could just contain the last arg.

If you chose a solution which changes how current args work, that might be worse than making a backwards incompatible API change, as the code would all still compile, but programs could break in unexpected ways.

**Comment by sorcix** [comment]
You're right.

The best solution is to break the API and follow the RFC.Changing irc.Trailing to irc.Trailing() should be pretty easy to update. Code that depends on the length of irc.Params may be a little more work, though.

Let's do this. I will implement this change in a separate branch and try to reach people using the package (at the very least those mentioned in the README) for comments, before pushing it to master.

**Comment by sorcix** [comment]
I should change the import comment to make people use a versioned URL instead of github.com/sorcix/irc. Let's do that first.

**Comment by sorcix** [comment]
This is taking long. I realise that I'm not very good at taking decisions like this. Preventing breaking changes is the reason I kept this package so simple.

I hope to get some input from @nickvanw, @Alligator, @TheCreeper and other users of this package. There may be a non-breaking solution that we're overlooking.

**Comment by belak** [comment]
No worries. I moved a few branches around so I can at least use this and can switch back to using your version when some sort of fix (one way or another) is merged in.

**Comment by belak** [comment]
Is this still being considered? I'd like to move forward if possible.

**Comment by belak** [comment]
The only other option I can think of would be to add a HasTrailing field which would say whether or not Trailing came with the message, however, this requires every client to be aware of the fact that Trailing is just another param.

**Comment by sorcix** [comment]
I have closed merge request #11 as I don't want to break backwards compatibility.

Options I'm still considering:

1. Provide a function that gives you the full list:

    ```
    func (m *Message) AllParams() []string {
      // copy m.Params and m.Trailing into a new slice
    }
    ```

2. Create a single slice containing everything as you did in #11, then provide subslices:

    ```
    Allparams []string
    Params []string // = Allparams[:len(Allparams)-2] in case there is a Trailing argument
    Trailing string // = Allparams[len(Allparams)-1] in case there is a Trailing argument
    ```

3. Anything else that doesn't break the API in a horrible way

Option 2 would be more efficient, case 1 is cleaner. Both don't really fix the problem the way your merge request did, but breaking the API is not an option.

**Comment by belak** [comment]
I think option one would be the least intrusive. I'd be willing to work on that.

**Comment by sorcix** [comment]
Yes, true. But if you use that for every message it means copying every single argument list, almost duplicating the amount of memory used for handling a message.

A third option could be calling a method `Combine` and then use m.Params.

    func (m *Message) Combine() {
      m.Params = append(m.Params, Trailing);
    }

But this option, too, becomes a problem when sending messages.

**Comment by belak** [comment]
Looking back at all the previous comments, it seems like we have to pick one of the following:

* Break backwards compatibility (already vetoed)
* Copy params into a new slice (possible performance issues)
* Duplicate values in the struct (not clear where values should be copied to/from when sending)
* Provide an option to mangle the params, adding the trailing value (also breaking sending, if we want messages to match)

The way I see it, either the API starts getting inconsistent, or backwards compatibility has to be broken for this bug to be fixed.

What about providing a separate branch (next, or similar) and posting a notification on master that the API will be breaking eventually? Or providing a way to version the API, possibly through gopkg.in or a similar service?

**Comment by sorcix** [comment]
There are some parts of your code that I would like to merge into master. Your way of parsing the arguments is a lot better, for example. A separate branch would certainly be doable if the difference is small enough.

**Comment by belak** [comment]
If there's a path forward for this bug, I would do the work. Rewriting the message parsing would be trivial. However I'd rather not wait another 3 months only to find out that there isn't a plan for this.

**Comment by Aerdan** [comment]
The way the IRC protocol works, `CMD foo` and `CMD :foo` are equivalent as long as there are no spaces in `foo`. Consequently, having the space-included parameter in the same slice is a non-issue as long as it's acceptable to omit the colon for the parameter when there is no space in it.

**Comment by belak** [comment]
Is there a path forward for this bug? The fact that we need to do something like this to respond to a ping in a way that works cross servers is crazy...

```
	if m.EmptyTrailing || m.Trailing != "" {
		client.Encode(&irc.Message{
			Command: "PONG",
			Params:  m.Trailing,
		})
	} else if len(m.Params) > 0 {
		client.Encode(&irc.Message{
			Command: "PONG",
			Params:  []string{m.Params[len(m.Params)-1]},
		})
	} else {
		return errors.New("Invalid PING")
	}

	return nil
}
```

This check needs to be done almost everywhere for code to be correct.

If it was integrated into m.Params, the same result would look like this, essentially dropping the need for the extra two checks on m.Trailing and m.EmptyTrailing:

```
	if len(m.Params) > 0 {
		client.Encode(&irc.Message{
			Command: "PONG",
			Params:  []string{m.Params[len(m.Params)-1]},
		})
	} else {
		return errors.New("Invalid PING")
	}

	return nil
```

I understand breaking backwards compatibility is bad in most circumstances, but leaving it like this makes it easier to write broken clients because most people will only bother coding for a single server, which makes it harder to share code between different bots without the `m.EmptyTrailing || m.Trailing != ""` check every time they want to use the last argument.

**Comment by sorcix** [comment]
I have pushed branch `v2.x` where the `Params` slice contains the trailing parameter. It's not using @belak's rewrite as that code had a performance issue. (My code still has the issue with multiple spaces though, so may be replaced if there are improvements in that pull request.)

Planning to test this on a few servers first, as I'm wondering how the different IRC servers behave if every single message contains a parameter prefixed with a colon. I've had some issues with that while writing my Java irc library.

Before merging that branch into master, we'll need a document describing the breaking change and how to update code.

**Comment by belak** [comment]
Thanks for working on this. Are there any plans to use something like gopkg.in?

**Comment by sorcix** [comment]
Yeah, let's do that.

This might actually be a good way to handle upgrading too. When we change the import comment in doc.go to a versioned URL, people that use the package will see an error including the new (versioned) import URL. If we keep that in master for a few months, most users should have migrated.

**Comment by sorcix** [comment]
I have renamed the v2 branch to support gopkg.in: gopkg.in/sorcix/irc.v2

**Comment by belak** [comment]
Awesome! Thanks for doing this.

**Comment by sorcix** [comment]
I'll close this issue. Feel free to open a new one if there's anything wrong with the implementation in v2.
